name: Cypress Tests

on:
  push:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: electron
          build: npm run build
